### ISSUE TITLE
Latest binary is broken (binaries release for accelerated cpu solo mining)

### ISSUE THREAD

**Issue by faudi** [0xbitcoin/0xbitcoin-miner#10]
Hi Ad,
that's what I get when I try to run the updated executable you just released

`pkg/prelude/bootstrap.js:1172
      throw error;
      ^

Error: Cannot find module './build/Release/cpuminer'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:534:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1269:46)
    at Function.Module._load (module.js:464:25)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\snapshot\0xbitcoin-miner\0xbitcoinminer-accel.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)`

**Comment by 0xbitcoin** [comment]
Hello I think this is resolved in the brand new dist for 'gpu' branch, please check and let me know !  I do believe this was an active  bug 13 hours ago that was resolved.

**Comment by faudi** [comment]
Hi!
Unfortunately, the executable (1.4.1) starts and I can mine in solo mode. But if I start pool mining an assertion failed is thrown as it starts mining
![assertion_failed](https://user-images.githubusercontent.com/36740123/36589639-4aca8702-188c-11e8-8c31-553351a78641.png)
