### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by ThomasTwen** [0xbitcoin/0xbitcoin-miner#2]
Running the miner on 0xBTC

The miner displays the following error in the miner command prompt

Unhandled rejection Error: Transaction was not mined within 50 blocks, please make sure your transaction was properly send. Be aware that it might still be mined!
    at C:\snapshot\0xbitcoin-miner\node_modules\web3-core-method\src\index.js:0:0
    at tryCatcher (C:\snapshot\0xbitcoin-miner\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (C:\snapshot\0xbitcoin-miner\node_modules\bluebird\js\release\promise.js:497:31)
    at Promise.module.exports.Promise._settlePromise (C:\snapshot\0xbitcoin-miner\node_modules\bluebird\js\release\promise.js:555:18)
    at Promise.module.exports.Promise._settlePromise0 (C:\snapshot\0xbitcoin-miner\node_modules\bluebird\js\release\promise.js:600:10)
    at Promise.module.exports.Promise._settlePromises (C:\snapshot\0xbitcoin-miner\node_modules\bluebird\js\release\promise.js:679:18)
    at Async._drainQueue (C:\snapshot\0xbitcoin-miner\node_modules\bluebird\js\release\async.js:125:16)
    at Async._drainQueues (C:\snapshot\0xbitcoin-miner\node_modules\bluebird\js\release\async.js:135:10)
    at Immediate.__dirname.Async.drainQueues [as _onImmediate] (C:\snapshot\0xbitcoin-miner\node_modules\bluebird\js\release\async.js:16:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

The error log is empty. stdout appears to have found a solution at the approximate time at which that error was displayed - this seems consistent with the malformed transaction error.

"2018:02:15:18:53:24Giving mined solution to network interface 0x05ac257cf530fd87ce85a7373d9cab943ecdc66200d3f9a8e3a5069ae7be602d\\n","2018:02:15:18:53:24Popping queued mining solution [object Object]\\n","2018:02:15:18:53:24Submitting Solution 0x0000006fb41dda248fea91a5970f22cc7ac2ba4ed6098950fc7fefa5d633b87c\\n"

**Comment by ThomasTwen** [comment]
May or may not be this tx: https://www.etherchain.org/tx/e0d590f4fbb3bd76f511a6ce2354b68f19f0188e55734bb558e5ae9c964e5758

**Comment by daevski** [comment]
I see the same thing every time the miner submits for reward. I tried upping the gasprice, but it didn't help. I'm still mining, and the submissions are making it to the blockchain, but this far none have been accepted. I assume I'm just not the first to solve the challenge on all the attempts thus far.
