### ISSUE TITLE
'nvcc' is not recognized on Windows 10

### ISSUE THREAD

**Issue by jsappme** [0xbitcoin/0xbitcoin-miner#22]
I installed Cuda but I am still getting the following error when trying to run yarn:

```
  compile cuda file on linux
  'nvcc' is not recognized as an internal or external command,
  operable program or batch file.
```

**Comment by jsappme** [comment]
same issue on my ubuntu box:

```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/nimiq/0xbitcoin-miner/build'
  CXX(target) Release/obj.target/cpuminer/cpp/cpuminer/addon.o
  CXX(target) Release/obj.target/cpuminer/cpp/cpuminer/cpuminer.o
  CXX(target) Release/obj.target/cpuminer/cpp/cpuminer/solver.o
  CC(target) Release/obj.target/cpuminer/cpp/cpuminer/sha3.o
  SOLINK_MODULE(target) Release/obj.target/cpuminer.node
  COPY Release/cpuminer.node
  RULE binding_gyp_gpuminer_target_cuda_on_linux_0 Release/obj.target/gpuminer/geni/cuda_sha256d.o
/bin/sh: 1: nvcc: not found
gpuminer.target.mk:10: recipe for target 'Release/obj.target/gpuminer/geni/cuda_sha256d.o' failed
make: *** [Release/obj.target/gpuminer/geni/cuda_sha256d.o] Error 127
make: Leaving directory '/home/nimiq/0xbitcoin-miner/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nimiq/0xbitcoin-miner
gyp ERR! node -v v9.7.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by jsappme** [comment]
Update: I was able to install cuda on the ubuntu using:

sudo apt install nvidia-cuda-toolkit

but I am still getting an error while running npm i:

```
 RULE binding_gyp_gpuminer_target_cuda_on_linux_0 Release/obj.target/gpuminer/geni/cuda_sha256d.o
In file included from /home/nimiq/0xbitcoin-miner/cpp/cuda_sha256d.cu:10:0:
/home/nimiq/0xbitcoin-miner/cpp/./miner.h:15:68: fatal error: curl/curl.h: No such file or directory
compilation terminated.
gpuminer.target.mk:10: recipe for target 'Release/obj.target/gpuminer/geni/cuda_sha256d.o' failed
make: *** [Release/obj.target/gpuminer/geni/cuda_sha256d.o] Error 1
make: Leaving directory '/home/nimiq/0xbitcoin-miner/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nimiq/0xbitcoin-miner
gyp ERR! node -v v9.7.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 0xbitcoin-miner@1.5.23 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 0xbitcoin-miner@1.5.23 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nimiq/.npm/_logs/2018-03-06T21_07_21_661Z-debug.log
```

**Comment by IgorUserowsky** [comment]
can recreate the error on ubuntu box. 

/bin/sh: 1: nvcc: not found gpuminer.target.mk:10: recipe for target 'Release/obj.target/gpuminer/geni/cuda_sha256d.o' failed make: *** [Release/obj.target/gpuminer/geni/cuda_sha256d.o] Error 127

**Comment by barrystyle** [comment]
try installing cuda toolkit (https://developer.nvidia.com/cuda-downloads)..
the error messages are fairly terse, if it can't see nvcc - set your path correctly (https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#faq2).

'reddit: helping those not by learning, but by providing more people to ask'

**Comment by robertjuh** [comment]
i have this problem but i have an AMD GPU, and i wish to try the CPU miner as my GPU is pretty much dying...
